In [ ]:
# Week 2 - Landslide Dataset
# Baseline: Logistic Regression
# Improved Model: GBDT + Feature Interaction

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [17]:
df = pd.read_csv("../data/landslide_dataset.csv")
df.head()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
0,206.181018,58.275001,0.892798,0.339463,4.390047,0.099975,1,0,0,0
1,218.887334,36.679801,0.657147,0.360355,4.141029,0.832443,1,0,0,1
2,181.850867,31.363874,0.673362,0.221697,5.311891,0.023062,1,0,0,1
3,228.716199,38.995134,0.618666,0.489502,4.581928,0.785176,1,0,0,1
4,179.951067,42.998205,0.836966,0.118580,5.518862,0.450499,1,0,0,0

In [28]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Dataset'i oku
df = pd.read_csv("../data/landslide_dataset.csv")

# Feature ve target ayır
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Eğer kategorik sütun varsa sayısala çevir
X = pd.get_dummies(X, drop_first=True)

# Veriyi train/test olarak ayır
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Model oluştur
model = LogisticRegression(max_iter=1000)

# Modeli eğit
model.fit(X_train, y_train)

# Tahmin yap
y_pred = model.predict(X_test)

# Sonuçları yazdır
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.7366666666666667

Classification Report:

              precision    recall  f1-score   support

           0       0.82      0.82      0.82       441
           1       0.50      0.52      0.51       159

    accuracy                           0.74       600
   macro avg       0.66      0.67      0.66       600
weighted avg       0.74      0.74      0.74       600

In [29]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)

In [30]:
from sklearn.model_selection import train_test_split

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_poly, y, test_size=0.3, random_state=42
)

In [31]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

gbdt_model = GradientBoostingClassifier()
gbdt_model.fit(X_train_p, y_train_p)

y_pred_p = gbdt_model.predict(X_test_p)

print("GBDT Accuracy:", accuracy_score(y_test_p, y_pred_p))
print("\nClassification Report:\n", classification_report(y_test_p, y_pred_p))

GBDT Accuracy: 0.7483333333333333

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.84      0.83       441
           1       0.53      0.50      0.51       159

    accuracy                           0.75       600
   macro avg       0.67      0.67      0.67       600
weighted avg       0.74      0.75      0.75       600

In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "Baseline (Logistic Regression)": [
        accuracy_score(y_test, y_pred),
        precision_score(y_test, y_pred, average="weighted"),
        recall_score(y_test, y_pred, average="weighted"),
        f1_score(y_test, y_pred, average="weighted")
    ],
    "Improved (GBDT + Feature Interaction)": [
        accuracy_score(y_test_p, y_pred_p),
        precision_score(y_test_p, y_pred_p, average="weighted"),
        recall_score(y_test_p, y_pred_p, average="weighted"),
        f1_score(y_test_p, y_pred_p, average="weighted")
    ]
})

results

,Metric,Baseline (Logistic Regression),Improved (GBDT + Feature Interaction)
0,Accuracy,0.736667,0.748333
1,Precision,0.738805,0.743900
2,Recall,0.736667,0.748333
3,F1 Score,0.737702,0.745939